# Site settings
title: Python Minifier - GLAD432
description: "Python minifier online tool reduces Python code size by removing unnecessary characters, improving script performance."
url: "https://glad432.github.io"
